[program:sinau-devops]
command=/var/www/sinau-devops/start.sh
directory=/var/www/sinau-devops
user=root
autostart=true
autorestart=true
stderr_logfile=/var/log/sinau-devops/err.log
stdout_logfile=/var/log/sinau-devops/out.log
environment=NODE_ENV="production",PORT="3000"
